Update github workflows

diff --git a/.github/workflows/my-jobs.yml b/.github/workflows/my-jobs.yml
--- a/.github/workflows/my-jobs.yml
+++ b/.github/workflows/my-jobs.yml
@@ -8,14 +8,19 @@ on:
 jobs:
 
   build_image:
-    runs-on: [self-hosted, some-label]
+    runs-on: [ self-hosted, some-label ]
     steps:
       - uses: actions/checkout@v3
       - name: Build Docker image
         run: docker build -t myapp:lastest -f CICD-DockerRunner.API/Dockerfile .
-      - name: Stop the Container
-        run: docker stop myappContainer
-      - name: Remove the Container
-        run: docker rm myappContainer
+      - name: Check if container exists
+        run: docker ps -a | grep myappContainer | grep -q "Exited" > /dev/null
+        if: ${{ steps.Check_if_container_exists.outputs.container_exists == 'true' }}
+        uses: actions/shell@v3
+        with:
+          - name: Stop the Container
+            run: docker stop myappContainer || echo "Container stopping failed"
+          - name: Remove the Container
+            run: docker rm myappContainer || echo "Container removal failed"
       - name: Run Docker container
         run: docker run -d -p 4000:8080 --name myappContainer myapp:lastest
